### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by WDBell** [JorjMcKie/PyMuPDF-optional-material#5]
I just clicked on pymupdf-1.11.0.0-py34-x64.zip and received a diagnostic about the file being too big to display. When I did a 'save as' the file I received was said to be corrupted.

**Comment by JorjMcKie** [comment]
I just tried it  - works fine with me.
Message "too big to display" is completely normal. On this screen click the "download" button. 
Unpack the downloaded zip file and enter the dir containing setup.py.
There, open a command prompt and enter ´py setup.py install`. My output of this follows:

    C:\Users\Jorj\Desktop\fitz>py setup.py install
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fitz
    copying fitz\__init__.py -> build\lib\fitz
    copying fitz\fitz.py -> build\lib\fitz
    copying fitz\utils.py -> build\lib\fitz
    running install_lib
    copying build\lib\fitz\fitz.py -> C:\Python34-64\Lib\site-packages\fitz
    copying build\lib\fitz\utils.py -> C:\Python34-64\Lib\site-packages\fitz
    copying build\lib\fitz\__init__.py -> C:\Python34-64\Lib\site-packages\fitz
    byte-compiling C:\Python34-64\Lib\site-packages\fitz\fitz.py to fitz.cpython-34.pyc
    byte-compiling C:\Python34-64\Lib\site-packages\fitz\utils.py to utils.cpython-34.pyc
    byte-compiling C:\Python34-64\Lib\site-packages\fitz\__init__.py to __init__.cpython-34.pyc
    running install_data
    copying fitz\_fitz.pyd -> C:\Python34-64\Lib\site-packages\fitz
    running install_egg_info
    Removing C:\Python34-64\Lib\site-packages\fitz-1.11.0-py3.4.egg-info
    Writing C:\Python34-64\Lib\site-packages\fitz-1.11.0-py3.4.egg-info
    
    C:\Users\Jorj\Desktop\fitz>

**Comment by WDBell** [comment]
Thanks for your response.

Yes, when I clicked on the 'Download' button from the page that said 'too big' I was able to proceed as you describe. I can't remember having seen one of these before though.  But I'm not getting any younger. :)

Still, I  would like to point out that when I returned to the previous page and did (in Windows) a 'Save link as' on what appears to be the same file the result was a download of a 48KB runt rather than the 2642 KB zip that one should have received. I would suggest that the links might be renamed.

**Comment by JorjMcKie** [comment]
If you enter "Save link as" this will of course save the link and not the link **target**.
I will clarify the text in that respect.
The reasons for this admittedly a little awkward download procedure are

- I want to keep all those binaries in **one** rpository (as opposed to creating a separate one for each Python and bitness combination).
- I want to offer a way to just download the probably one and only installation set somebody is interested in (and not all 14 - that would mean a several dozens MB beast).

Have fun with PyMuPDF!

As per age I will probably beat you ;-)

**Comment by WDBell** [comment]
------- 70 -------

**Comment by JorjMcKie** [comment]
ok, you win (65)
